"""empty message

Revision ID: 139addc12392
Revises: 2cf5ddb3bbda
Create Date: 2020-09-02 22:27:06.830253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '139addc12392'
down_revision = '2cf5ddb3bbda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('userid',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('userteam',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('userteam',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
        batch_op.alter_column('userid',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)

    # ### end Alembic commands ###
