"""empty message

Revision ID: 33ccac7e95bb
Revises: 6f9be7410b7a
Create Date: 2020-09-21 23:18:29.465647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33ccac7e95bb'
down_revision = '6f9be7410b7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usergroup', sa.String(length=30), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('usergroup')

    # ### end Alembic commands ###
