"""empty message

Revision ID: 3523d78cec14
Revises: 04c972f35de2
Create Date: 2020-09-07 23:17:43.897520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3523d78cec14'
down_revision = '04c972f35de2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('idea', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userteam', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_idea_userteam_user'), 'user', ['userteam'], ['userteam'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('idea', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_idea_userteam_user'), type_='foreignkey')
        batch_op.drop_column('userteam')

    # ### end Alembic commands ###
