"""empty message

Revision ID: 730ab7c31c36
Revises: 8469e9ec7a02
Create Date: 2020-09-02 22:08:44.377805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '730ab7c31c36'
down_revision = '8469e9ec7a02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userid', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('userteam', sa.String(length=30), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_user_userid'), ['userid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_userid'), type_='unique')
        batch_op.drop_column('userteam')
        batch_op.drop_column('userid')

    # ### end Alembic commands ###
