"""empty message

Revision ID: 7689022c593c
Revises: 0aca011bcedd
Create Date: 2020-08-18 21:12:41.557091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7689022c593c'
down_revision = '0aca011bcedd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prod_id', sa.String(length=30), server_default='1', nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_column('prod_id')

    # ### end Alembic commands ###
