"""empty message

Revision ID: bff65a53bec2
Revises: 
Create Date: 2020-10-13 21:53:53.493656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bff65a53bec2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('companyID', sa.String(length=10), nullable=False),
    sa.Column('companyName', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company')),
    sa.UniqueConstraint('companyID', name=op.f('uq_company_companyID'))
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('companyID', sa.String(length=10), nullable=False),
    sa.Column('prodID', sa.String(length=20), nullable=False),
    sa.Column('prodName', sa.String(length=100), nullable=False),
    sa.Column('avgqty', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product')),
    sa.UniqueConstraint('companyID', 'prodID', name=op.f('uq_product_companyID'))
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('usergroup', sa.String(length=30), nullable=False),
    sa.Column('userteam', sa.String(length=30), nullable=False),
    sa.Column('userid', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('email', name=op.f('uq_user_email')),
    sa.UniqueConstraint('userid', name=op.f('uq_user_userid'))
    )
    op.create_table('idea',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ideaNum', sa.String(length=30), nullable=False),
    sa.Column('ideaType', sa.String(length=50), nullable=False),
    sa.Column('ideaTitle', sa.String(length=200), nullable=False),
    sa.Column('priceBefore', sa.Float(), nullable=True),
    sa.Column('priceAfter', sa.Float(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('regDate', sa.DateTime(), nullable=False),
    sa.Column('userid', sa.String(length=150), nullable=False),
    sa.Column('userName', sa.Integer(), nullable=False),
    sa.Column('editDate', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['userName'], ['user.username'], name=op.f('fk_idea_userName_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_idea'))
    )
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idea_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('regDate', sa.DateTime(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('editDate', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['idea_id'], ['idea.id'], name=op.f('fk_feedback_idea_id_idea'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userid'], ['user.userid'], name=op.f('fk_feedback_userid_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feedback'))
    )
    op.create_table('ideaProd',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ideaNum', sa.Integer(), nullable=True),
    sa.Column('companyID', sa.String(length=10), nullable=False),
    sa.Column('prodID', sa.String(length=30), nullable=False),
    sa.Column('ideaStatus', sa.String(length=30), nullable=True),
    sa.Column('effectBegin', sa.DateTime(), nullable=True),
    sa.Column('effectEnd', sa.DateTime(), nullable=True),
    sa.Column('estSavings', sa.Float(), nullable=True),
    sa.Column('agentID', sa.String(length=150), nullable=False),
    sa.ForeignKeyConstraint(['ideaNum'], ['idea.ideaNum'], name=op.f('fk_ideaProd_ideaNum_idea')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ideaProd'))
    )
    op.create_table('idea_voter',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('idea_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idea_id'], ['idea.id'], name=op.f('fk_idea_voter_idea_id_idea'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_idea_voter_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'idea_id', name=op.f('pk_idea_voter'))
    )
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('regDate', sa.DateTime(), nullable=False),
    sa.Column('editDate', sa.DateTime(), nullable=True),
    sa.Column('idea_id', sa.Integer(), nullable=True),
    sa.Column('feedback_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedback.id'], name=op.f('fk_comment_feedback_id_feedback'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['idea_id'], ['idea.id'], name=op.f('fk_comment_idea_id_idea'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.userid'], name=op.f('fk_comment_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comment'))
    )
    op.create_table('feedback_voter',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('feedback_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedback.id'], name=op.f('fk_feedback_voter_feedback_id_feedback'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_feedback_voter_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'feedback_id', name=op.f('pk_feedback_voter'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedback_voter')
    op.drop_table('comment')
    op.drop_table('idea_voter')
    op.drop_table('ideaProd')
    op.drop_table('feedback')
    op.drop_table('idea')
    op.drop_table('user')
    op.drop_table('product')
    op.drop_table('company')
    # ### end Alembic commands ###
