"""empty message

Revision ID: d0727a34bba5
Revises: 3523d78cec14
Create Date: 2020-09-07 23:27:52.227807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0727a34bba5'
down_revision = '3523d78cec14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('idea', schema=None) as batch_op:
        batch_op.drop_constraint('fk_idea_userteam_user', type_='foreignkey')
        batch_op.drop_column('userteam')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('idea', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userteam', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_idea_userteam_user', 'user', ['userteam'], ['userteam'], ondelete='CASCADE')

    # ### end Alembic commands ###
