"""empty message

Revision ID: eecf96691f3b
Revises: fd589ea57bf1
Create Date: 2020-09-07 21:02:23.976818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eecf96691f3b'
down_revision = 'fd589ea57bf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('idea', schema=None) as batch_op:
        batch_op.drop_constraint('uq_idea_userid', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('idea', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_idea_userid', ['userid'])

    # ### end Alembic commands ###
