"""empty message

Revision ID: f242a8194aea
Revises: 8995ce1a2add
Create Date: 2020-08-18 21:05:46.228898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f242a8194aea'
down_revision = '8995ce1a2add'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company', sa.String(length=30), server_default='1', nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_column('company')

    # ### end Alembic commands ###
